%bcond_without tests
%bcond_without weak_deps
%bcond_with vendored

%global cargo_vendor_file %(if [ -n "%{?cargo_vendor_source}" ]; then echo "%{cargo_vendor_source}"; elif [ 0%{?with_vendored} -ne 0 ] || [ -f "%{_sourcedir}/cargo-vendor.tar.gz" ]; then echo "cargo-vendor.tar.gz"; else echo ""; fi)

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^@(InstallationPrefix)/.*$
%global __requires_exclude_from ^@(InstallationPrefix)/.*$

%global cargo_registry @(InstallationPrefix)/share/cargo/registry

Name:           @(Package)
Version:        @(Version)
Release:        @(RPMInc)%{?dist}%{?release_suffix}
Summary:        ROS @(Name) package

License:        @(License)
@[if Homepage and Homepage != '']URL:            @(Homepage)@\n@[end if]@
Source0:        %{name}-%{version}.tar.gz
%if "%{cargo_vendor_file}" != ""
Source1:        %{cargo_vendor_file}
%endif
@[if NoArch]@\nBuildArch:      noarch@\n@[end if]@

@[for p in Depends]Requires:       @p@\n@[end for]@
@[for p in sorted(BuildDepends + ['python3-pallet-patcher', 'rust-packaging'])]BuildRequires:  @p@\n@[end for]@
@[for p in Conflicts]Conflicts:      @p@\n@[end for]@
@[for p in Replaces]Obsoletes:      @p@\n@[end for]@
@[for p in Provides]Provides:       @p@\n@[end for]@
@[if TestDepends]@\n%if 0%{?with_tests}
@[for p in TestDepends]BuildRequires:  @p@\n@[end for]@
%endif@\n@[end if]@
@[if Supplements]@\n%if 0%{?with_weak_deps}
@[for p in Supplements]Supplements:    @p@\n@[end for]@
%endif@\n@[end if]@

%description
@(Description)

%prep
%autosetup -p1

# Handle vendored cargo sources
if [ -n "%{?SOURCE1}" ] && [ -f "%{SOURCE1}" ]; then
  echo "Using vendored cargo sources from %{SOURCE1}"
  tar -xf "%{SOURCE1}"
fi

%cargo_prep -N
sed -i 's/^offline = true$/offline = false/' .cargo/config.toml

if [ -d "vendor" ]; then
  echo "Configuring cargo to use local vendor directory"
  cat << 'EOF' > pallet-patcher.toml
[build]
offline = true

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
EOF
else
  pallet-patcher --output-format=toml Cargo.toml %{cargo_registry} > pallet-patcher.toml
fi

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "@(InstallationPrefix)/setup.sh" ]; then . "@(InstallationPrefix)/setup.sh"; fi
%cargo_build -- --config pallet-patcher.toml

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "@(InstallationPrefix)/setup.sh" ]; then . "@(InstallationPrefix)/setup.sh"; fi
%cargo_install -- --config=pallet-patcher.toml --config="install.root='%{buildroot}@(InstallationPrefix)'"

%if 0%{?with_tests}
%check
%cargo_test -- --config=pallet-patcher.toml || echo "RPM TESTS FAILED"
%endif

%files
@[for lf in LicenseFiles]%license @lf@\n@[end for]@
@(InstallationPrefix)

%changelog@
@[for change_version, (change_date, main_name, main_email) in changelogs]
* @(change_date) @(main_name) <@(main_email)> - @(change_version)
- Autogenerated by Bloom
@[end for]
