%if %(test -f "%{_sourcedir}/cargo-vendor.tar.gz" && echo 1 || echo 0)
%bcond_without cargo_vendor
%else
%bcond_with cargo_vendor
%endif

%{?!ros_distro:%global ros_distro @(Rosdistro)}
%global pkg_name @(Name)
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

%global cargo_registry @(InstallationPrefix)/share/cargo/registry

Name:           @(Package)
Version:        @(Version)
Release:        @(RPMInc)%{?dist}
Summary:        ROS %{pkg_name} package

License:        @(License)
@[if Homepage and Homepage != '']URL:            @(Homepage)@\n@[end if]@
Source0:        %{name}-%{version}.tar.gz
%if 0%{?with_cargo_vendor}
Source1:        cargo-vendor.tar.gz
%endif
@[if NoArch]@\nBuildArch:      noarch@\n@[end if]@

BuildRequires:  bloom-rpm-macros
BuildRequires:  python3-pallet-patcher
BuildRequires:  rust-packaging

%{?bloom_package}

%description
@(Description)


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
@[if not NoArch]Provides:       %{name}%{?_isa} = %{version}-%{release}@\n@[end if]@
Requires:       %{name}-runtime@[if not NoArch]%{?_isa}@[end if] = %{version}-%{release}

%description devel
@(Description)


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
@(Description)


%prep
%autosetup -p1

%if 0%{?with_cargo_vendor}
echo "Using vendored cargo sources from %{SOURCE1}"
tar -xf %{SOURCE1}
%endif

%cargo_prep -N
pallet-patcher --output-format=toml Cargo.toml %{cargo_registry} %{?with_cargo_vendor:vendor} %{_datadir}/cargo/registry > pallet-patcher.toml


%generate_buildrequires
%bloom_buildrequires


%build
%cargo_build -- --config pallet-patcher.toml


%install
%cargo_install -- --config=pallet-patcher.toml --config="install.root='%{buildroot}@(InstallationPrefix)'"

%if 0%{?with_cargo_vendor}
install -d -m 0755 %{buildroot}@(InstallationPrefix)/share/@(Name)/cargo
cp -a vendor %{buildroot}@(InstallationPrefix)/share/@(Name)/cargo/
%endif


%if 0%{?with_tests}
%check
%cargo_test -- --config=pallet-patcher.toml || echo "RPM TESTS FAILED"
%endif


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
@[for lf in LicenseFiles]%license @lf@\n@[end for]@
%{bloom_prefix}


%changelog@[for change_version, (change_date, main_name, main_email) in changelogs]
* @(change_date) @(main_name) <@(main_email)> - @(change_version)
- Autogenerated by Bloom
@[end for]@
